export { default as PageImportantText } from './pageImportantText'
export { default as PageTitle } from './pageTitle'
export { default as PageShowInfo } from './pageShowInfo'
export { default as PageLoading } from './pageLoading'
export { default as PageShowElement } from './pageShowElement'